FROM golang:1.8.1

RUN go get github.com/Masterminds/glide
WORKDIR /go/src/github.com/ory-am/hydra

ADD ./glide.yaml ./glide.yaml
ADD ./glide.lock ./glide.lock
RUN glide install --skip-test -v

ADD . .
RUN go install .
